name: Main Github Actions

on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10.14
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.14
        cache: 'pip'
    - name: Install dependencies
      run: |
        make install
    - name: Format code isort
      uses: isort/isort-action@v1
    - name: Format code black
      uses: psf/black@stable
    - name pylint
      run: |
          pip install pylint
        	pylint --disable=R,C,W **/*.py



    